name: mol-meltingpoint
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - joblib
  - jupyter
  - notebook
  - rdkit
  - pip
  - pip:
      - xgboost
      - lightgbm
